# Computed scores for the section on the role of the stemma codicum

In [1]:
from stemmadist.utils.utils import load_tree

## Design the different tress

In [2]:
stemma_ref = "((F,E)C,(H,(I,G)D)B)A;"

print(load_tree(stemma_ref).ascii_art())

        ┌─F
    ┌─C─┤
    │   └─E
──A─┤
    │   ┌─H
    └─B─┤
        │   ┌─I
        └─D─┤
            └─G

In [3]:
stemma_1 = "((F,E)C,(H,(G)D)B)A;"

In [4]:
stemma_2 = "(((G,I)F,E)C,(H,D)B)A;"

print(load_tree(stemma_2).ascii_art())

            ┌─G
        ┌─F─┤
    ┌─C─┤   └─I
──A─┤   └─E
    │   ┌─H
    └─B─┤
        └─D

In [5]:
stemma_3 = "((F,A)C,(H,(I,G)D)B)E;"
print(load_tree(stemma_3).ascii_art())

        ┌─F
    ┌─C─┤
    │   └─A
──E─┤
    │   ┌─H
    └─B─┤
        │   ┌─I
        └─D─┤
            └─G

In [6]:
stemma_4 = "((F,E)C,(H,(B,G)D)I)A;"
print(load_tree(stemma_4).ascii_art())

        ┌─F
    ┌─C─┤
    │   └─E
──A─┤
    │   ┌─H
    └─I─┤
        │   ┌─B
        └─D─┤
            └─G

## Compute the different scores between the stemma (matrix)

In [7]:
from stemmadist.main import compute_distance, AVAILABLE_DISTANCES

In [8]:
distances = {}
for distance in AVAILABLE_DISTANCES:
    distances[distance] = {}
    for ix, stemma in enumerate([stemma_ref, stemma_2, stemma_3, stemma_4]):
        print(distance)
        print(compute_distance(stemma_ref, stemma, distance_name=distance))
        distances[distance][ix] = compute_distance(stemma_ref, stemma, distance_name=distance)

rf
0
rf
4
rf
2
rf
2
rf_jaccard
2.0
rf_jaccard
0.6666666666666666
rf_jaccard
1.5
rf_jaccard
1.5
matching_split
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
0
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
matching_split
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'G', 'I'}, {'E'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'E', 'G', 'I', 'C'}, {'D', 'B', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'G', 'I'}, {'E'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'E', 'G', 'I', 'C'}, {'D', 'B', 'H'})]
6
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'G', 'I'}, {'E'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'E', 'G', 'I', 'C'}, {'D', 'B', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'G', 'I'}, {'E'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'E', 'G', 'I', 'C'}, {'D', 'B', 'H'})]
matching_split
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'A', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'A', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
2
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'F', 'A', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'I', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'F', 'A', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
matching_split
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'B', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'B', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
2
!!!
[({'H'}, {'G', 'I', 'D'}), ({'H'}, {'G', 'B', 'D'})]
!!!
[({'H'}, {'G', 'I', 'D'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'H'}, {'G', 'B', 'D'})]
!!!
[({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'}), ({'E', 'F', 'C'}, {'D', 'B', 'G', 'I', 'H'})]
adjacency_matrix
0.0
adjacency_matrix
0.31426968052735443
adjacency_matrix
0.2222222222222222
adjacency_matrix
0.31426968052735443
graph_edit_distance
0
graph_edit_distance
4
graph_edit_distance
1.0
graph_edit_distance
1.0
signed_similarity
0.0
signed_similarity
19.0
signed_similarity
10.5
signed_similarity
20.0

In [14]:
import pandas as pd


distance_scores = pd.DataFrame(distances)

distance_scores

,rf,rf_jaccard,matching_split,adjacency_matrix,graph_edit_distance,signed_similarity
0,0,2.000000,0,0.000000,0.0,0.0
1,4,0.666667,6,0.314270,4.0,19.0
2,2,1.500000,2,0.222222,1.0,10.5
3,2,1.500000,2,0.314270,1.0,20.0

In [17]:
distance_scores.assign(**distance_scores.iloc[:, :].rank(axis = 0, ascending = True).astype(int))

,rf,rf_jaccard,matching_split,adjacency_matrix,graph_edit_distance,signed_similarity
0,1,4,1,1,1,1
1,4,1,4,3,4,3
2,2,2,2,2,2,2
3,2,2,2,3,2,4